### ISSUE TITLE
Looking for doc

### ISSUE THREAD

**Issue by mcanevet** [kobolog/gorb#18]
Hello,

This project looks like the missing link to my swarm cluster to have floating IPs automagically configured to point to my docker service. However I'm a little bit stuck with the lack of documentation to start playing with this cool stuff.
By looking at the other issues, it looks like I have to start a container with `kobolog/gorb` image on my router with `--net=host` and `--privileged kobolog/gorb`.

if I use want to use consul as my services are already registered in it with `gliderlabs/registrator`, do I still have to launch a `kobolog/gorb-docker-link` container on my docker hosts?

Do I have to run the `gorb` container with some kind of consul-template so that the configuration is automatically refreshed?

Best Regards

**Comment by kobolog** [comment]
I'm going to get to writing some docs quite soon, so stay tuned! Regarding this issue: so GORB will register service balancer endpoints with Consul for you. If your services are already registered with Consul, this will mean that whenever you use Consul's SD it will give you non-balanced endpoint instead. The GORB support is very straightforward – you pass a `-c http://<consul-host>:<port>` to GORB daemon and it will call `/service/register` and `/service/deregister` for all virtual services registered with it.
