### ISSUE TITLE
Enhancement / Nanomsg

### ISSUE THREAD

**Issue by lucmichalski** [kobolog/gorb#25]
Hi guys,

Hope you are doing well !

It would be great to implement the surveyor pattern from the NanoMsg to gorb, or some other scalable communication protocols. (Repo: https://github.com/go-mangos/mangos)

Have a good week end !

Cheers,
Luc

**Comment by kobolog** [comment]
Hey there,

I don't quite see how these protocols fit into the project. Could you please elaborate on what the usecase would be?

**Comment by kobolog** [comment]
I'm going to close it since I don't understand how Nanomsg fits in here.
