### ISSUE TITLE
the rest return message is in text/plain content type

### ISSUE THREAD

**Issue by dzhang-msx** [kobolog/gorb#31]
Since we already have return the message in a JSON format, it would be nice to have a option to set the Content-Type of returned message to `application/json`. The current return message `Content-Type →text/plain; charset=utf-8`

I was trying to change in [main.go](https://github.com/kobolog/gorb/blob/24d476a1f195be441760cbd57c64aa34d828b702/main.go#L85) wasn't able to get it to work.

**Comment by kobolog** [comment]
Resolved by commit 76989161ef5dae71cdd2bb93647fca8aa1fa5558. I've also changed the dependency management to be Glide to use vendoring, which is generally easier and more straightforward.
