### ISSUE TITLE
support DR mode

### ISSUE THREAD

**Issue by leslie-wang** [kobolog/gorb#37]
I've created https://github.com/tehnerd/gnl2go/issues/4. It should be fixed easily. Hope it can be enhanced in GORB too.

**Comment by leslie-wang** [comment]
https://github.com/tehnerd/gnl2go/issues/4 has been fixed. Seems like we can change in this project. Do you want me to submit a fix?

**Comment by kobolog** [comment]
Hey @leslie-wang, yeah that would be great!

**Comment by leslie-wang** [comment]
can you open permission for me?

**Comment by kobolog** [comment]
Just create a pull request, you don't need any permissions for that.

**Comment by kobolog** [comment]
Closed by #38.
