### ISSUE TITLE
Interesting project!

### ISSUE THREAD

**Issue by bketelsen** [kobolog/gorb#4]
How about a write up on the December Gopher Academy Blog post series?
https://docs.google.com/spreadsheets/d/1H0rj7TJo0t8GWyNdGwEc6bGcDj6UgJUN42JtAtbPMrk/edit?usp=sharing

we get thousands of views for every article - great way to get some visibility for the project!

**Comment by kobolog** [comment]
I think this is a great idea. I'll take a look at some of the recent blog
posts and draft something up to share with you. How does it sound?

**Comment by bketelsen** [comment]
Perfect!

**Comment by alexw23** [comment]
Looks good - would cut out a middle man (haproxy) for sure. I really like the sound of the consul intergration.

**Comment by bketelsen** [comment]
Ping -- still time to sign up.

**Comment by kobolog** [comment]
Hey – got overwhelmed by my official job a little here :/ Any chance to get into January post series instead?
