### ISSUE TITLE
Add BGP Advertisement Options When VIP Is Added

### ISSUE THREAD

**Issue by albamc** [kobolog/gorb#41]
It would be nice to gorb sending BGP advertisement when VIP is added.

**Comment by albamc** [comment]
There are three ways to do it.

1) Send BGP Advertise directly from gorb.
2) Call the API of external BGP Daemon (ex. Gobgp / quoga) in gorb.
3) Add a separate daemon like gorb-docker-link. This daemon reads the IPVS information and reports it to the external BGP daemon.

I'd like to add a simple daemon that works with gobgp in 3).
- If BGP peer is disconnected due to the characteristics of BGP Protocol, BGP Daemon can not be restarted frequently because all routes to this peer are deleted.
Therefore, it would be advantageous to separate the BGP Daemon function into separate daemons.
- An external bgp server would like gobgp once.

**Comment by kobolog** [comment]
@albamc do you think you'll have time to contribute this feature?

**Comment by albamc** [comment]
@kobolog 
Our team made changes for this issues but too many source codes were changed...
We don't think our changes is accepted to gorb main codes.
Sorry for missing update issues.
