### ISSUE TITLE
Your video https://www.youtube.com/watch?v=oFsJVV1btDU  and ab utility that use in your video

### ISSUE THREAD

**Issue by MJayakumar** [kobolog/gorb#55]
Dear Andrey Sibiryov, 

I watched your excellent video https://www.youtube.com/watch?v=oFsJVV1btDU
You are using a utility ab 
Your command line in that video is ab -n 1000 -c 32 http://$....
Where to get this ab utility please?
This is the first time I am learning this utility. Very interested to put hands on to this utility.
Can I please request you to kindly let me know the url for instructions as how to use ab utility and download instructions please. 
Much appreciated 
M Jay

**Comment by pyaillet** [comment]
Hi,

ab is a tool from the apache foundation and is available right [here](https://httpd.apache.org/docs/2.4/en/programs/ab.html)

**Comment by MJayakumar** [comment]
Thank you so much
Much appreciated
M Jay

**Comment by MJayakumar** [comment]
Dear Pyaillet, 
Thank you.
Does ab available on user space?
1 Million transactions per sec is what I am looking to inject with the tool. 
It is getting limited before that.
Not sure if the bottleneck is because of kernel space.
How to increase it to generate million transactions per sec please
Thank you

**Comment by pyaillet** [comment]
Hi,
I'm not sure to understand your questions.
But I think you could use the tool [hey](https://github.com/rakyll/hey) now.
Maybe you could address them your questions.

**Comment by kobolog** [comment]
I'm going to close this one since it's not an issue with the project.
